/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppLoginRouteImport } from './routes/_app.login'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppSignupRouteImport } from './routes/_app.signup'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as AppRolesIndexRouteImport } from './routes/_app.roles.index'
import { Route as AppRolesNewRouteImport } from './routes/_app.roles.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesNewRoute = AppRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AppLoginRoute
  '/privacy': typeof AppPrivacyRoute
  '/signup': typeof AppSignupRoute
  '/u/$slug': typeof USlugRoute
  '/roles/new': typeof AppRolesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/roles/': typeof AppRolesIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AppLoginRoute
  '/privacy': typeof AppPrivacyRoute
  '/signup': typeof AppSignupRoute
  '/u/$slug': typeof USlugRoute
  '/': typeof AppIndexRoute
  '/roles/new': typeof AppRolesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/roles': typeof AppRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/signup': typeof AppSignupRoute
  '/u/$slug': typeof USlugRoute
  '/_app/': typeof AppIndexRoute
  '/_app/roles/new': typeof AppRolesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/roles/': typeof AppRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/u/$slug'
    | '/roles/new'
    | '/api/auth/$'
    | '/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/u/$slug'
    | '/'
    | '/roles/new'
    | '/api/auth/$'
    | '/roles'
  id:
    | '__root__'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/login'
    | '/_app/privacy'
    | '/_app/signup'
    | '/u/$slug'
    | '/_app/'
    | '/_app/roles/new'
    | '/api/auth/$'
    | '/_app/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  USlugRoute: typeof USlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/new': {
      id: '/_app/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AppRolesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoginRoute: typeof AppLoginRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppSignupRoute: typeof AppSignupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRolesNewRoute: typeof AppRolesNewRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLoginRoute: AppLoginRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppSignupRoute: AppSignupRoute,
  AppIndexRoute: AppIndexRoute,
  AppRolesNewRoute: AppRolesNewRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  USlugRoute: USlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
